### PR TITLE
Allow usage of nimble_options 1.0

### PR DESCRIPTION
**Pull request by edennis**
I changed the requirements to match Broadway: https://github.com/dashbitco/broadway/blob/24533d4cc9ee23827cf289e6630f514c975ad922/mix.exs#LL31C39-L31C39

### CODE REVIEW

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Comment by nicanor** [comment]
Hi.
I tried to get this change but I couldn't.
Is it possible that this change is not released in hex?
Anything I can do to help?

BTW: Thank you for this library!

**Comment by wojtekmach** [comment]
v0.7.3 is out!

**Comment by nicanor** [comment]
That was so fast. Thanks 👏

**Pull request merged**
