### PR TITLE
Update the example app to work with latest Broadway and Broadway SQS

### PR DESCRIPTION
**Pull request by philss**
Also add the example app to our CI pipeline.

### CODE REVIEW

**Comment by josevalim** [comment]
I think we can also clean up and remove the comments of the config files, WDYT?

**Comment by josevalim** [comment]
Something else we could do is to change the example app to use Broadway.DummyProducer. This way, you no longer need to define a TestClient that has an empty receive_message. WDYT?

**Comment by philss** [comment]
> Something else we could do is to change the example app to use Broadway.DummyProducer. This way, you no longer need to define a TestClient that has an empty receive_message. WDYT?

I think the intention of the TestClient is to demonstrate that the `BroadwaySQS.Producer` is working good if you define a custom SQSClient. I'm not sure if replacing with the DummyProducer will be beneficial here because if we do it won't be testing anything related to the SQS producer. WDYT?

**Comment by josevalim** [comment]
Tge example app is meant to be an example for other devs, no? if so, best practice today is the dummy producer. The functionality is tested on sqs itself (if not, it should!).

**Comment by philss** [comment]
@josevalim yes, makes sense! I changed to use `Broadway.DummyProducer` :+1:

**Review by josevalim — APPROVED** [review]

**Pull request merged**
